// <auto-generated />
namespace ToDoEvents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class xd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xd2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711270923276_xd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
